### ISSUE TITLE
Many false positive predictions

### ISSUE THREAD

**Issue by Sundragon1993** [iminfine/Deep-DIM#2]
Hello there, 
Thank you for your fantastic work, I've modified your code to run on custom templates and search images, however, the results don't seem quite right as it predicted a lot of false-positive heatmaps on images that don't contain the template we're looking for.
Any suggestion on this matter?

**Comment by iminfine** [comment]
If you just modified the inputs and the implementation is correctly, the prediction of DIM should be accurate and better than other template matching methods. In your case, please double check the inputs by drawing the template and search image pairs.

**Comment by Sundragon1993** [comment]
Thank you for your comment, 

Yes, you're right as your algorithm is very rigorous and precise in most of my experiments, It dominates other SOTA algorithms like QATM or DDIS (tested), however, when running it on a random image that doesn't contain the template it will produce false-positive heatmaps and a wrong bounding box like the following sample:
![1](https://user-images.githubusercontent.com/9301684/170438089-b2453f2d-420e-4e50-b32f-c7e35d9f7251.png)

I was wondering if you have any idea to filter out these FP heatmaps and don't show the prediction (red bb) on the final result?

**Comment by iminfine** [comment]
I get you right now. Please check the maximum values in there false-positive heatmaps, these values should be much small than the normal cases (the search region contains the template). And set a suitable threshold, if the maximum value is below it then don't output the bb.
